### ISSUE TITLE
Purpose of ResourcesNotMatched report?

### ISSUE THREAD

**Issue by thikade** [IBM/websphere-cct#11]
Hi Dennis,

I have noticed that the Resources report additionally generates a report called *ResourcesNotMatched*.
I have run ConfigReports for a few different cell dumps (using the default properties), but all the while both *Resources* report and *ResourcesNotMatched* seem both identical in size and content. That does not seem right or useful!?

During a cell dump comparison I watched out for resources (eg Datasources) that were added or removed in the second, newer dump. These are listed the resources report using the yellow `N/A` report key correctly. But finding those in a large Resource report is quite cumbersome. Wouldn't it make sense to put those exclusively in the *ResourcesNotMatched* report?

Regards
Thomas

**Comment by riddlemo** [comment]
Hi Thomas,
        ResourcesNotMatched is obsolete.  I need to remove it. 


Regards,
Dennis 


Dennis Riddlemoser, Accelerated Value Specialist
World Wide IBM Software Accelerated Value Program
Phone: (720) 342-5689
Email: riddlemo@us.ibm.com
Visit IBM Software Accelerated Value Program Online

**Comment by thikade** [comment]
Hi Dennis,

ok, makes sense.   

What about my idea of putting resources that *do exist only in one of the 2 cell dumps* into a separate file or section, in terms of an enhancement request? It would make spotting those items much easier than looking thru the complete resource report.  

Also, such new or deleted resources are not part of the *differences-only* resource report you get with setting `ReportOnlyMismatched=All`

**Comment by riddlemo** [comment]
Hi Thomas,
        The Cell Summary report should be enhanced instead as the purpose 
of it is to summarize cell servers and resources.  Feel free to either 
implement this or open an issue for it and I will look into it when I have 
time. 


Regards,
Dennis 


Dennis Riddlemoser, Accelerated Value Specialist
World Wide IBM Software Accelerated Value Program
Phone: (720) 342-5689
Email: riddlemo@us.ibm.com
Visit IBM Software Accelerated Value Program Online

**Comment by riddlemo** [comment]
Removed report.  This should improve performance when using ReportList=All.
