### ISSUE TITLE
New reports for multiple resources

### ISSUE THREAD

**Issue by thikade** [IBM/websphere-cct#13]
Opening this issue to track the implementation of the following report resources:
- URLProvider
- URL
- J2CConnectionFactory
- J2CAdminObject
- MQConnectionFactory
- MQQueueConnectionFactory
- MQTopicConnectionFactory
- MQQueue
- MQTopic

**Comment by riddlemo** [comment]
Integrated changes.  Will be publishing a new release today.  Closing issue.
