### ISSUE TITLE
Need to copy the values from one cell to another cell and the values of one node to another within a cell

### ISSUE THREAD

**Issue by hasanmehdirizvi** [IBM/websphere-cct#16]
Hi Dennis,

We have discussed this earlier as well on a call. I am not sure whether how to copy the configuration of a cell to another cell when moving from DEV to INT or higher environment. 
Also, if there is a difference in comparing two nodes then how can we copy the value of one node on another. I remember you said that we can do this with the current version but I couldn't find it anything in the documentation. Please guide me on this.

Thanks 
Hasan Mehdi
MetLife

**Comment by riddlemo** [comment]
Hi Hasan,
        CCT will produce sample wsadmin correction scripts which will 
accomplish what you are looking for in most instances.  The scripts will 
provide syntax to update existing configuration values but they will not 
create or delete any configuration items.  Generation of these scripts is 
enabled by setting OutputScripts=True.  There will be files with the 
extension of .py created which correspond to the differences seen in the 
.html reports.  Please see pages 36-39 in the PDF for full details. Please 
let me know if I can assist further.


Regards,
Dennis 


Dennis Riddlemoser, Accelerated Value Specialist
World Wide IBM Software Accelerated Value Program
Email: riddlemo@us.ibm.com
Visit IBM Software Accelerated Value Program Online

**Comment by riddlemo** [comment]
Please reopen if you have additional questions on this topic.
