### ISSUE TITLE
Question: RegEx Pattern Attribute Value substitution

### ISSUE THREAD

**Issue by arejay73** [IBM/websphere-cct#18]
I need help understanding the functionality of ReplaceForMatch and ReplaceWith in Report Parameters.  I have a situation where I am comparing configurations across multiple environments like Dev, Test, and Prod.  I know ahead of time that I will have values that differ because they are in different environments.

For example, Database attribute.  I would like to normalize the values for the Database property based on our naming convention so I do have a bunch of "false" positives.

So, I thought I could use the ReplaceForMatch and ReplaceWith, but I am unable to get this to work.

Dev Attribute - database_name : Dev Attribute Value - DB1dSrv
Test Attribute - database_name : Test Attribute Value - DB1tSrv
Prod Attribute - database_name : Prod Attribute Value - DB1pSrv

I wanted to create matching rules like so it would normalized the "Database Name" attribute value to "DB1Srv"

Is this possible?

**Comment by riddlemo** [comment]
If you add all three in ReplaceForMatch properties, it will ignore them for matching purposes.  The logic will replace any instance of the string with a ".*." for matching purposes.  When there are replacement strings, there will be two regex matches. This is due each string has regular expression replacements and is compared with the other.  

Example, you have MyServer1 and MyAppSrv1 in the same config attribute for different elements  and you want these to match.  

ReplaceForMatch:1=Server
ReplaceForMatch:2=AppSrv

This will cause My.*1 to be matched with MyAppSrv1 and My.*1 to be matched with MyServer1.  Each of these will match.

ReplaceWith does not work if regular expression constructs are not used.  For example:

ReplaceForMatch:1=Server
RepalceWith:1=AppSrv

MyServer1 will change to MyAppSrv1 and match but then MyAppSev1 will fail to compare with MyServer1 as no replacement was done.  

Instead you could do:
ReplaceForMatch:1=Server
RepalceWith:1=......
ReplaceForMatch:2=AppSrv
RepalceWith:2=......

This will cause My......1 to be matched with MyAppSrv1 and My.......1 to be matched with MyServer1.  Each of these will match.

The two comparisons are necessary to account for a scenario like this.  Assume there are two attributes; value1, value2.

ReplaceForMatch:1=value

If there is only one comparison, value1 (which will turn into .*1) will match with value2 but if the attributes order is reversed value2 will not match value one so the comparison will fail even though it should succeed.

**Comment by arejay73** [comment]
Thanks for the explanation.  Let's see if I get it.  For example, I have the following table with an attribute:

| Application Deployment (WebSphereAPP.ear) |                |                                                                                         |                                                                                          |                                                                                          |
|-------------------------------------------|----------------|-----------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------|
| Attribute                                 | Config Matches | $(WAS_INSTALL_ROOT)/systemApps/WebSphereAPP.ear Cell: serverdmgrDEV1Cell01-200730105030 | $(WAS_INSTALL_ROOT)/systemApps/WebSphereAPP.ear Cell: serverdmgrTEST1Cell01-200730105030 | $(WAS_INSTALL_ROOT)/systemApps/WebSphereAPP.ear Cell: serverdmgrPROD1Cell01-200730105030 |
| appContectIDforSecurity                   | No             | href:serverdmgrDEV1Cell01/WebSphereApp                                                  | href:serverdmgrTEST1Cell01/WebSphereApp                                                  | href:serverdmgrPROD1Cell01/WebSphereApp                                                  |

I want to remove the key words DEV, TEST and PROD from the attribute values so they don't match and show a 'false' positive, because I know they will be different.  I would use the following rules:

```
ReplaceForMatch:1=DEV
ReplaceWith:1=...
ReplaceForMatch:2=TEST
ReplaceWith:2=....
ReplaceForMatch:3=PROD
ReplaceWith:3=....

```
I would not do something like this:
```
ReplaceForMatch:1= serverdmgrDEV1Cell01
ReplaceWith:1= serverdmgr1Cell01
ReplaceForMatch:2=serverdmgrTEST1Cell01
ReplaceWith:2=serverdmgr1Cell01
ReplaceForMatch:3=serverdmgrPROD1Cell01
ReplaceWith:3=serverdmgr1Cell01

```
And finally, I would set the property:
`DoNotMatchNames=false`

**Comment by riddlemo** [comment]
Yes, that looks correct.  Replacing with "..." should work since all three replacement strings are three characters long.  Please reopen if you have additional questions on this topic.
