### ISSUE TITLE
Another question: In WAS ND there are multiple app servers 

### ISSUE THREAD

**Issue by vadim-rosenstein** [IBM/websphere-cct#19]
Good afternoon, Dennis.
Dennis, could you tell us please, if we have WAS Network Deployment with 5 application servers (5 JVMs), server1, sererv2, etc. Of course, the .cfg file contains configuration for all 5 JVMS. We need to create a report ONLY for one JVM, let's say for server3. How can we do that? Not only that, Dennis if we need to compare server3 from one environment with server3 from a different environment, what steps do we need to take.
Thanks a lot, in advance.

**Comment by riddlemo** [comment]
Two compare entities from two cells, you need to run ConfigDump.py against each cell.  You would need to have ConfigReport.py pull in both .cfg files into the reporting either by placing them both in the same directory and running ConfigReport.py from that directory or by specifying them in the ConfigurationDumpFiles property.

To compare one server (you can compare one but it really is just a report of the configuration at that point), specify the following properties.

ReportList=MyReport

MyReport:ReportType=Server
MyReport:Title=My Report
MyReport:Clusters:1=
MyReport:Servers:1=MyCellName::MyServerName
MyReport:FileName=MyReport

To add in another server from another cell add the following properties.
MyReport:Servers:2=MyOtherCellName::MyOtherServerName

You can have any number of servers specified just make sure the ID is unique.  The IDs in the sample above are 1 & 2.

**Comment by vadim-rosenstein** [comment]
Thanks a lot, Dennis for your quick reply. The name of the Application server we'd like to create a report on is CAPSServer. This is what we tried in ConfigReport.properties

CAPSServer:ReportType=Server
CAPSServer:Title=CAPS Servers
CAPSServer:Clusters:1=
CAPSServer:Servers:1=CAPSCell::CAPSServer
CAPSServer:ReportList=All
#CAPSServer:ReportOnlyMismatched=All

it worked like a charm, it created a server report only for CAPSServer. But  when we try to produce a report for CAPSServer's Resources we used these properties

CAPSServer:ReportType=Server
CAPSServer:Title=CAPS Servers
CAPSServer:Clusters:1=
CAPSServer:Servers:1=CAPSCell::CAPSServer
CAPSServer:ReportList=Resources
CAPSServer:FileName=CAPS_Servers
#CAPSServer:ReportOnlyMismatched=All

The CAPS_Server report came out empty and Resources report contain 4 more application server that we're trying to eliminate. What would you suggest, Dennis.
Thanks a million once again.

**Comment by riddlemo** [comment]
The ReportList property within a report definition is not documented and not used the way you think it is.  It is for limiting the tables created in an HTML report for debugging and development purposes.  I need to change the name and remove it from the samples to avoid confusion.  

If you are looking to run the built in Resources report, either don't specify the ReportList at all or specify ReportList=Resources.

If you are trying to create a custom resources report, it is similar syntax but REPORT_NAME:Type needs to be the resource type you want to compare (e.g. DataSource).  Also the selection syntax is a bit different as well.  

Here is a sample I have in ConfigReport.properties
EJBTimerDataSource:ReportType=DataSource
EJBTimerDataSource:Title=EJB Timer DataSource
EJBTimerDataSource:Scope:1=Node
EJBTimerDataSource:Resources:1=.*::.*::DefaultEJBTimerDataSource
EJBTimerDataSource:FileName=EJBTimerDataSource

Note, unlike Server reports, a scope has to be specified and the ID ("1" in the sample above) needs to match.  A server does not have resources.  A resource may be scoped (only visible to) to a server, however.  This is how the configuration repository is structured.

**Comment by riddlemo** [comment]
Please reopen issue if you have additional questions.

**Comment by vadim-rosenstein** [comment]
Dennis, sorry for the late response, but thank you so much and have a great day!
