### ISSUE TITLE
Does wcct run on Windows?

### ISSUE THREAD

**Issue by rlesses** [IBM/websphere-cct#26]
All evidence tells me it does not. I would like confirmation. Thanks!

**Comment by riddlemo** [comment]
WCCT does work on Windows.  I have done all of my development from Windows.  Unless you have a Unix style sh in the path, it must be run from the same directory all the WCCT scripts are placed in.  This is a Python limitation.  Also, Python 2.7 is required due to Jython being based on Python 2.7.  See the PDF for more details.

**Comment by rlesses** [comment]
Thank you.

Richard Lesses
Team Lead/Technical Lead, Maximo Systems & Integration Support
IBM | Maximo Support
office: 720.342.7502
email: ***@***.******@***.***>
twitter: @rlesses

From: riddlemo ***@***.***>
Sent: Thursday, March 31, 2022 10:43 AM
To: IBM/websphere-cct ***@***.***>
Cc: Richard Lesses ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [IBM/websphere-cct] Does wcct run on Windows? (Issue #26)

WCCT does work on Windows. I have done all of my development from Windows. Unless you have a Unix style sh in the path, it must be run from the same directory all the WCCT scripts are placed in. This is a Python limitation. Also, Python 2.7 ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd


WCCT does work on Windows. I have done all of my development from Windows. Unless you have a Unix style sh in the path, it must be run from the same directory all the WCCT scripts are placed in. This is a Python limitation. Also, Python 2.7 is required due to Jython being based on Python 2.7. See the PDF for more details.
