### ISSUE TITLE
.cfg file is not getting generated after running ConfigDump.py

### ISSUE THREAD

**Issue by cnukwas** [IBM/websphere-cct#7]
Hello Dennis,

Thanks for the tool an I tried running the dump command with below syntax without making any changes to any properties after downloading wcct tool on one of our AIX servers.

/opt/IBM/V90/WebSphere/AppServer/profiles/Dmgr01/bin/wsadmin.sh -f /opt/cctest/ConfigDump.py ConfigDump_Output.log

The command ran fine but didn't generate MyCell.cfg or any other .cfg files at /opt/cctest/ location.

Am I missing anything here?

**Comment by riddlemo** [comment]
Hi,  it should have generated a configuration dump by the name of ConfigDump_Output.log  If you specify a single parameter after ConfigDump.py, it is the name of the configuration dump file.

**Comment by cnukwas** [comment]
Thanks for the update, wasn't aware that the first parameter was the .cfg file data.
